name: video_editor_2
description: |
  A flutter package for editing video with fully customizable UI.
  Supports crop, trim, rotation and cover selection.
version: 3.1.1
repository: https://github.com/Alberto-Monteiro/video_editor
homepage:

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^2.0.1
  get_thumbnail_video:
    git:
      url: https://github.com/moELSmokhraty27/video_thumbnaill.git
    
  video_player:
    git:
      url: https://github.com/Mina-Zarif/packages.git
      path: packages/video_player/video_player
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp
